version: "2.0"
services:
  corona-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - SESSION_SECRET=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=corona
      - DB_PASSWORD=corona
      - DB_DATABASE=corona
      - DB_READ_REPLICA_HOST=db
      - API_TOKEN=token
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: corona
      POSTGRES_PASSWORD: corona
